### ISSUE TITLE
Getting error on loading library

### ISSUE THREAD

**Issue by harshmittal2810** [WontakKim/SimpleStreaming#1]
I am unable to run app after permission dialog
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class "com.github.wontakkim.simplestreaming.vuv.YuvI420Converter" on path: DexPathList[[zip file "/data/app/com.github.wontakkim.simplestreaming.sample-Rt0aTRFOnhjUvqT1AJlJlg==/base.apk"],nativeLibraryDirectories=[/data/app/com.github.wontakkim.simplestreaming.sample-Rt0aTRFOnhjUvqT1AJlJlg==/lib/arm, /data/app/com.github.wontakkim.simplestreaming.sample-Rt0aTRFOnhjUvqT1AJlJlg==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

System.loadLibrary("yuv");

**Comment by WontakKim** [comment]
Thanks for reporting the issue. I put wrong file path in jni. If you change "com.github.wontakkim.simplestreaming.vuv.YuvI420Converter" to "com.github.wontakkim.simplestreaming.yuv.YuvI420Converter" might be work. I'll push in an hour. Thanks for reporting again.

**Comment by WontakKim** [comment]
I fixed the issue and if it happen again, let me know :)
