### ISSUE TITLE
Is your repo still working? 

### ISSUE THREAD

**Issue by chienpm304** [WontakKim/SimpleStreaming#2]
I am encountering with streaming from screen with MediaCodec and Virtual diasplay? It is possible to apply your project to my problem? Give me some guilde plz. Thank you!

**Comment by WontakKim** [comment]
Seems no one use my library but it has to be work this repo.

Im not sure Im properly understand your question.
In conclusion, you have some problem while streaming on your virtual display. Am I correct?

**Comment by chienpm304** [comment]
I use MediaProjection to record the screen, I can get output buffer but I don't know if it is fine to stream this buffer using your library?

**Comment by WontakKim** [comment]
It is not master peace of library for streaming such as FFMPEG. It is targeted for YUV420 data, RTMP and AVC for compact and better performance.

Doesn't matter MediaProjection or CameraPreview something. Important thing is, which format data want you to pass to streaming server and protocols. I recommend you to create example code and test that I attached sample code below and than you will get answer.

RtmpPublisher streaming = new RtmpPublisher(640, 480);
streaming.setUrl("rtmp://127.0.0.1:1935/live/livestream");
streaming.prepare();
streaming.start();
streaming.putVideoData(data);

The key thing is, you should pass YUV420 format of data to RtmpPublisher object.
