### ISSUE TITLE
May I have your recent change project? Project delay is a bit high

### ISSUE THREAD

**Issue by ghost** [WontakKim/SimpleStreaming#6]

**Comment by WontakKim** [comment]
Im so sorry for late response 🙏 I worked on video streaming company before and it was easy to get self motivation before but currently not easy to get self motivation again. Im so glad to hear my code help someone's work(Actually I may think so easily about this project). Of course you use or modify this work, also it's combined YUV, RTMP etc. It's not only my work so use this project and someday (soon or later) I will rework this project 👍
